Manage multiple network interfaces
taktik/flowr-desktop pull request #18
Opened 2019-10-21 16:17 UTC by denishamann

2019-10-23 06:59 UTC, lmancel requested changes
Only some logs to remove, and the build to fix (i.e run `npm i` and commit the new package-lock.json)

2019-10-23 06:59 UTC, lmancel commented on src/frontend/index.ts
> +      console.log('DENIS')
Remove log

2019-10-23 06:59 UTC, lmancel commented on src/frontend/index.ts
> +      console.log(ipAddress)
Remove log

2019-10-23 10:54 UTC, hubjac1 reviewed
Could you verify why the build is failing.
You should keep a listener on message "reciveMacAdress" because we have to ensure backward compatibility with Flowr 5.1 and Flowr 5.2.7

2019-10-23 10:55 UTC, hubjac1 requested changes
see my previous comments

2019-11-13 10:07 UTC, lmancel commented on src/frontend/index.ts
> +      evt.sender.send('receiveActiveMacAddress', activeMacAddress)
To guarantee backward compatibility, we should also send `evt.sender.send('receiveMacAddress', activeMacAddress)`

2019-11-13 10:11 UTC, lmancel requested changes

2019-11-13 10:11 UTC, lmancel commented on src/frontend/index.ts
> +      evt.sender.send('receiveActiveMacAddress', activeMacAddress)
(it would also return the active mac address)

2019-11-13 11:05 UTC, lmancel approved these changes

2019-11-13 11:06 UTC, lmancel requested changes
Automatic build fails because of an out-of-sync package-lock, please run `npm i` to update it

2019-11-13 11:53 UTC, lmancel approved these changes

2019-11-13 13:20 UTC, hubjac1 approved these changes

2019-11-13 13:21 UTC, merged