working implementation (few things to rollback)
taktik/flowr-desktop pull request #40
Opened 2021-11-24 07:52 UTC by JDuqn

2021-11-26 08:40 UTC, lmancel requested changes

2021-11-26 08:40 UTC, lmancel commented on src/frontend/src/players/abstractPlayer.ts
> +    this.store.persist()
Not necessary anymore, the store is persisted upon creation "automatically"

2021-11-26 08:40 UTC, lmancel commented on src/frontend/index.ts
> +    frame: false
Both values should not be hardcoded: they must depend on the value of vlc player's position.
Especially the `frame: false` that would completely remove the possibility to drag flowr-desktop's window.
This implies that if we notice that we did not open the window with the settings that match the ones received from flowr-frontend, then flowr's window must be destroyed and created again

2021-11-30 08:05 UTC, Azevedo-Dani commented
We store this settings in flowr-admin. We should also store that in user-preferences.json no ?

If no, there's a logic to know which setting we want store or not in user-preferences

2021-11-30 08:47 UTC, lmancel commented
> We store this settings in flowr-admin. We should also store that in user-preferences.json no ?
> 
> If no, there's a logic to know which setting we want store or not in user-preferences

It's defined in the player's store, and thus in player.json. Nothing else to be done.

2021-12-07 10:59 UTC, lmancel requested changes

2021-12-07 10:59 UTC, lmancel commented on src/frontend/src/players/vlc/player.ts
> +    const path = "C:\\projects\\bedside-vlc\\VlcForm\\bin\\Debug\\netcoreapp3.1\\VlcForm.exe"
🙅

2021-12-07 10:59 UTC, lmancel commented on src/launcher/index.ts
> +          app.relaunch();
```suggestion
          app.relaunch();
          app.quit();
```

2021-12-07 10:59 UTC, lmancel commented on src/launcher/index.ts
> +        if (flowrWindow.transparent && userPreferencesMerged.player.position !== PlayerPosition.BACKGROUND) {
Shouldn't this also cover the opposite case ?
```suggestion
        if ((flowrWindow.transparent && userPreferencesMerged.player.position !== PlayerPosition.BACKGROUND)
            || !flowrWindow.transparent && userPreferencesMerged.player.position !== PlayerPosition.FOREGROUND
        ) {
```

2021-12-07 15:00 UTC, lmancel approved these changes
Nothing else but a tiny style issue. Can be merged without it though

2021-12-07 15:00 UTC, lmancel commented on src/launcher/index.ts
> +import { WexondOptions } from "../wexond/main/app-window";
We should add prettier to the commit hook as well
```suggestion
import { WexondOptions } from '../wexond/main/app-window'
```

2021-12-08 08:51 UTC, Azevedo-Dani approved these changes

2021-12-08 09:10 UTC, merged